# fly.toml app configuration file generated for setlist-list on 2024-08-04T20:26:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'setlist-list'
primary_region = 'iad'

[build]

[env]
PORT = '8080'
SERVER_HOSTNAME = "https://setlist-list.fly.dev"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = "256mb"
