name: e2e

on:
  schedule:
    - cron: 0 * * * * # every hour

jobs:
  saas-template:
    name: Create saas starter template
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: |
          cargo install loco-cli
          ALLOW_IN_GIT_REPO=true LOCO_APP_NAME=saas LOCO_TEMPLATE=saas loco new
      - run: |
          cargo build
        working-directory: ./saas

  rest-api:
    name: Create stateless starter template
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: |
          cargo install loco-cli
          ALLOW_IN_GIT_REPO=true LOCO_APP_NAME=restapi LOCO_TEMPLATE=rest-api loco new
      - run: |
          cargo build
        working-directory: ./restapi

  lightweight-service:
    name: Create stateless starter template
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: |
          cargo install loco-cli
          ALLOW_IN_GIT_REPO=true LOCO_APP_NAME=lightweight LOCO_TEMPLATE=lightweight-service loco new
      - run: |
          cargo build
        working-directory: ./lightweight
